### ISSUE TITLE
mock auth redirect does not work on non-standard port

### ISSUE THREAD

**Issue by kgeis** [kuali/research-coi#13]
The change made to use req.hostname (to work in conjunction with Express' "trust proxy" setting) instead of req.get('host') in mockAuthClient.js made it so that in the non-proxy case, redirects only go to the standard port (HTTP 80, HTTPS 443). This is because req.get('host') and req.get('X-Forwarded-Host') is the entire Host header (e.g. "localhost:8090") where req.hostname is just the name of the server.

I can't find any way that Express makes it easy to handle both cases without duplicating effort in "trust proxy".

**Comment by kgeis** [comment]
For comparison, Koa sets req.host and req.hostname when app.proxy is true.

**Comment by iambrandonn** [comment]
How about we change [this line](https://github.com/kuali/research-coi/blob/master/server/services/AuthService/mockAuthClient.js#L72) to this?

```
let returnToValue = encodeURIComponent(req.originalUrl);
```

It makes the assumption that the mock auth service is on the same host as COI... but it will be, right?

**Comment by kgeis** [comment]
I think that will work for me. @gouldner, can you test this?

**Comment by gouldner** [comment]
Tested in dev and on test server and works. 
Thanks! Brandon !!!

**Comment by iambrandonn** [comment]
This was included in 1512.
