### ISSUE TITLE
error if research-extensions defined without storage

### ISSUE THREAD

**Issue by kgeis** [kuali/research-coi#3]
If I have a research-extensions module but it does not export "storage" then I get the following error:

    /opt/phoebe/research-coi-1.0.1/server/controllers/DisclosureController.js:202
    put('/api/coi/disclosures/:id/financial-entities/:entityId', upload.array('att
                                                                       ^
    TypeError: Cannot call method 'array' of undefined
        at Object.init (/opt/phoebe/research-coi-1.0.1/server/controllers/DisclosureController.js:198:75)
        at Object.run (/opt/phoebe/research-coi-1.0.1/server/app.js:60:24)
        at Object.<anonymous> (/opt/phoebe/research-coi-1.0.1/server/bootstrap.js:21:5)

**Comment by iambrandonn** [comment]
research-extensions is where Kuali "the company" keeps proprietary code which won't be released.  As such the API for it will likely be volatile, as we assume we are the only ones using it.  So... while you're welcome to try creating your own research-extensions, long term its going to be a painful experience.  What are you trying to accomplish with your own research-extensions?

**Comment by kgeis** [comment]
I need to be able to hook into the Express API in order to set "trust proxy". It seems like your extensions is not designed to override just one thing. Express is configured by its API, and needing to modify research-coi code would make implementing it a non-starter.

**Comment by iambrandonn** [comment]
How about if you could set an environment variable called TRUST_PROXY, which if present is a string we pass to `app.set('trust proxy', <your string here>);`

**Comment by kgeis** [comment]
That would feed me for a day. I worry about having to come back to ask for an enhancement for any web server configuration. However, having it as an environment variable would make a cleaner line between code and configuration.

**Comment by iambrandonn** [comment]
Yeah, I understand. Because this is something that could potentially cause problems for many institutions we'll add it to the project.  It will be in the next release.  Thanks.
