### ISSUE TITLE
problem with redirect host when running behind proxy

### ISSUE THREAD

**Issue by kgeis** [kuali/research-coi#5]
mockAuthClient calls `req.get('host')` but should probably use `req.hostname`. This will make it work better [behind a proxy](http://expressjs.com/en/guide/behind-proxies.html).

> The value of req.hostname is derived from the value set in the X-Forwarded-Host header, which can be set by the client or by the proxy.

**Comment by iambrandonn** [comment]
The Core Authentication service should be available soon.  It should eliminate the need for the mockAuthClient.  However, if its not ready in time for the next release, we can make this change.
